version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - ./Backend/instance:/app/instance
    restart: always
    command: sh -c "./start.sh"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  nginx:
    build: ./Frontend
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
