version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/app:/app
      - ./Backend/instance:/app/instance
    restart: always
    command: sh -c "chmod +x start.sh && ./start.sh"

  nginx:
    build: ./Frontend
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./Frontend/Static:/usr/share/nginx/html
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
