services:
  backend:
    build: ./Backend
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    restart: always

  nginx:
    build: ./Frontend
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
