version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - ./Backend/mydatabase.db:/app/mydatabase.db  # подключаем базу к хосту
    restart: always
    command: >
      sh -c "python init_db.py && python app.py"  # инициализируем БД перед запуском приложения

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always

volumes:
  static_volume:
