version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - ./Backend/mydatabase.db:/app/mydatabase.db 
    restart: always
    command: >
      sh -c "python init_db.py && python app.py" 

  nginx:
    build: ./Frontend
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
