services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always

volumes:
  static_volume:
