services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    networks:
      - dev

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    networks:
      - dev

networks:
  dev:
